version: "2"
plugins:
  rubocop:
    enabled: true
    channel: "rubocop-0-49"
    checks:
      Rubocop/Style/TrailingCommaInLiteral:
        enabled: false
    config:
      file: "alternate-rubocop-path.yml"
  sonar-php:
    enabled: true
  phpmd:
    enabled: true
exclude_patterns:
  - "tests/"
  - "database/"
